[package]
name = "export-vk"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
bincode = { workspace = true }
hex = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
num-bigint = "0.4"
regex = "1.10"
