[package]
name = "eth-sync-program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { workspace = true }
eth-sync-common = { path = "../common" }
sha2 = { workspace = true }
bls12_381 = { workspace = true, features = ["experimental"] }
group = "0.13"

# Fix for getrandom in zkVM
getrandom = { version = "0.2", features = ["custom"] }
