[workspace]
members = ["program", "script", "common", "export_vk"]
resolver = "2"

[workspace.dependencies]
sp1-zkvm = { version = "5.2.3" }
sp1-sdk = { version = "5.2.3" }
bls12_381 = "0.8.0"
sha2 = "0.9.9"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
bincode = "1.3"
typenum = "1.17"
generic-array = "0.14"
byteorder = "1.5"

[patch.crates-io]
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.9.9-sp1-4.0.0" }
bls12_381 = { git = "https://github.com/sp1-patches/bls12_381", tag = "patch-0.8.0-sp1-5.0.0-v2" }
